# =========================
# SERVER
# =========================
server.port=8080

# =========================
# SQL SERVER DATASOURCE
# =========================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DATN_SD42;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8
# =========================
# SQL INIT
# =========================
spring.sql.init.mode=always

# =========================
# JWT
# =========================
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# =========================
# LOGGING
# =========================
logging.level.com.base=DEBUG
logging.level.org.springframework.security=INFO