server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DATN_SD42;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 3000

    listener:
      simple:
        auto-startup: true
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
          multiplier: 2
          max-interval: 10000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  sql:
    init:
      mode: always
      encoding: UTF-8
  autoconfigure:
    exclude: [ ]

cloudinary:
  cloud-name: dlzulba2u
  api-key: 897496521236485
  api-secret: iUkO-cS7Rk0UGDzr2gb-tyPSF2M
  folder: products

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
    refresh-expiration: 604800000

  upload:
    temp-dir: uploads/temp
    base-url: http://localhost:8080

rabbitmq:

  queue:
    image-upload: image.upload.queue
  exchange:
    image: image.exchange
  routing-key:
    image-upload: image.upload.key

logging:
  level:
    com:
      base: DEBUG
    org:
      springframework:
        security: INFO